# Generated by Django 5.2.8 on 2025-11-09 20:05

from django.db import migrations, models

#Chequeamos que se haya realizado la migracion inicial para crear el modelo Centro
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('operacion', models.CharField(max_length=30)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
