# Generated by Django 5.2.7 on 2025-11-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pisoplanta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='centro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='centros/'),
        ),
    ]
